### ISSUE TITLE
Homeswitch works but it takes a few tries to back away from it

### ISSUE THREAD

**Issue by brownrb** [brownrb/myFP2EFirmware#29]
Homeswitch works but it takes a few tries to back away from it. 

Usually have to +10 two or three times before it disengages the homeswitch. 

Maybe this is a backlash setting issue on my side but it seemed to work fine in the previous release

**Comment by brownrb** [comment]
I have created a new branch 141.
I think I may have a quick fix for this, so I will code it into branch 141
When it is ready for testing, I will let you know,

regards
R

**Comment by brownrb** [comment]
I have the code for handling HPSW when backlash is enabled - uploaded to Branch 141
Can you please download branch 141 to test it please.

At the same time I fixed a couple of other things that were an issue
141
Change driverboard->halt() - no need to return stepcount
Fix for using Serial.print commands in MachineStateBacklash - changed to DebugPrint
Fix for 2nd network credential not being updated [readwificonifg() ]
Fix for Home Position Switch not working in Backlash
Fix for compilation warning message about driverboard->halt() - I have changed this to type void as there is no need for the function to return a value.

**Comment by hcomet** [comment]
I tried 141. Still have the same issue. Seems like the backing away from the switch after contact doesn't happen. I tried it with and without backlash enabled and has the same result for both.

I have a rack and pinion focuser with the Nema 14 - PG27 focuser. My backlash is set to 60 steps in both directions.

**Comment by hcomet** [comment]
Okay, I think I found the issue. I added a call to delayMicroseconds inside the loop that backs the focuser away from the homeswitch. I saw this was done in the backlash code. This seemed to fix things and the back away works and I'm no longer stuck on the homeswitch. 

I also noticed that the first move after the homeswitch back off also causes a backlash compensation which it shouldn't. So I also reset the direction to align with the switch backoff with set_focuserdirection.

Here's the State_SetHomePosition case with the two addtional lines:

```
    case State_SetHomePosition:                         // move out till home position switch opens
      DebugPrintln("State_SetHomePosition");
#ifdef HOMEPOSITIONSWITCH
      // check if display home position switch messages is enabled
      if ( mySetupData->get_showhpswmsg() == 1)
      {
        if (mySetupData->get_displayenabled() == 1)
        {
          myoled->oledtextmsg(HPMOVETILLOPENSTR, -1, false, true);
        }
      }
      // HOME POSITION SWITCH IS CLOSED - Step out till switch opens then set position = 0
      stepstaken = 0;                                   // Count number of steps to prevent going too far
      DebugPrintln(HPMOVETILLOPENSTR);
      DirOfTravel = !DirOfTravel;                       // We were going in, now we need to reverse and go out
      hpswstate = HPSWCLOSED;                           // We know we got here because switch was closed
      while ( hpswstate == HPSWCLOSED )
      {
        if ( mySetupData->get_reversedirection() == 0 )
        {
          steppermotormove(DirOfTravel);                // take 1 step
        }
        else
        {
          steppermotormove(!DirOfTravel);
        }

        delayMicroseconds(driverboard->getstepdelay()); // Ensure delay between steps

        stepstaken++;                                   // increment steps taken
        if ( stepstaken > HOMESTEPS )                   // this prevents the endless loop if the hpsw is not connected or is faulty
        {
          DebugPrintln(HPMOVEOUTERRORSTR);
          hpswstate = HPSWOPEN;
        }
        else
        {
          hpswstate = !(digitalRead(HPSWPIN));          // read state of HPSW
        }
      }
      DebugPrint(F(HPMOVEOUTSTEPSSTR));
      DebugPrintln(stepstaken);
      DebugPrintln(F(HPMOVEOUTFINISHEDSTR));
      ftargetPosition = 0;
      driverboard->setposition(0);
      mySetupData->set_fposition(0);
      
      mySetupData->set_focuserdirection(DirOfTravel);

      if ( mySetupData->get_showhpswmsg() == 1)         // check if display home position switch messages is enabled
      {
        if (mySetupData->get_displayenabled() == 1)
        {
          myoled->oledtextmsg(HPMOVEOUTFINISHEDSTR, -1, true, true);
        }
      }
#endif // #ifdef HOMEPOSITIONSWITCH
      MainStateMachine = State_DelayAfterMove;
      TimeStampDelayAfterMove = millis();
      DebugPrintln(STATEDELAYAFTERMOVE);
      break;
```

**Comment by brownrb** [comment]
Fixed in Master
